# Generated by Django 3.1.6 on 2021-02-06 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('others', 'others')], max_length=10)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=30)),
                ('city', models.CharField(help_text='location', max_length=20)),
                ('pincode', models.CharField(help_text='pincode', max_length=20)),
                ('joining', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(help_text='account balance')),
                ('createdon', models.DateTimeField(auto_now_add=True)),
                ('lastmodified', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customeraccount.customer')),
            ],
        ),
    ]
