# Generated by Django 3.1.6 on 2021-02-06 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customeraccount', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('debit', 'debit'), ('credit', 'credit')], max_length=20)),
                ('transactionamount', models.IntegerField()),
                ('created', models.DateField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customeraccount.customeraccount')),
            ],
        ),
    ]
