# Generated by Django 3.1.6 on 2021-02-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customeraccount', '0002_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
