# Generated by Django 3.1.6 on 2021-02-06 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customeraccount', '0003_auto_20210206_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='currbalance',
            field=models.IntegerField(default=0, help_text='balance currently'),
        ),
    ]
